apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-backend
  namespace: ecommerce
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
  connection-string: bW9uZ29kYi0wLm1vbmdvZGItc2VydmljZS5lY29tbWVyY2Uuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvZWNvbW1lcmNlLXRlbXBsYXRlP3JlcGxpY2FTZXQ9cnMwJnJldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQo=
  jwt-code: dGhpc19pc19hX3N1cGVyX2hhcmRjb3JlX3Bhc3N3b3Jk
